import AoHaruRide from '../assets/manga/aoharuride.png'
import AssassinationClassroom from '../assets/manga/assassinationclassroom.png'
import Bakuman from '../assets/manga/bakuman.png'
import Barakamon from '../assets/manga/barakamon.png'
import Beezlebub from '../assets/manga/beezlebub.png'
import Bleach from '../assets/manga/bleach.png'
import Buddha from '../assets/manga/buddha.png'
import DeathNote from '../assets/manga/deathnote.png'
import DetectiveConan from '../assets/manga/detectiveconan.png'
import Domekano from '../assets/manga/domekano.png'
import Doraemon from '../assets/manga/doraemon.png'
import Dragonball from '../assets/manga/dragonball.png'
import DungeonSeeker from '../assets/manga/dungeonseeker.png'
import ERankHealer from '../assets/manga/erankhealer.png'
import Evergreen from '../assets/manga/evergreen.png'
import Fairytail from '../assets/manga/fairytail.png'
import FullMetalAlchemist from '../assets/manga/fullmetalalchemist.png'
import Gintama from '../assets/manga/gintama.png'
import Haikyu from '../assets/manga/haikyu.png'
import HalfnHalf from '../assets/manga/half&half.png'
import Hanagimitokoisuruwatashi from '../assets/manga/hanagimitokoisuruwatashi.png'
import HibiChouchou from '../assets/manga/hibichouchou.png'
import Horimiya from '../assets/manga/horimiya.png'
import HunterxHunter from '../assets/manga/hunterxhunter.png'
import Inuyasha from '../assets/manga/inuyasha.png'
import KatekyoHitman from '../assets/manga/katekyohitman.png'
import Kenji from '../assets/manga/kenji.png'
import KoeNoKitachi from '../assets/manga/koenokitachi.png'
import LivingALeisureLifeInAWorldOfMagic from '../assets/manga/livingaleisurelifeinaworldofmagic.png'
import MagiSinbad from '../assets/manga/magi-sinbad.png'
import MinamotoKun from '../assets/manga/minamoto-kun.png'
import MissionOfLove from '../assets/manga/missionoflove.png'
import MousouTelepathy from '../assets/manga/mousoutelepathy.png'
import MyHeroAcademy from '../assets/manga/myheroacademy.png'
import Namaikazikari from '../assets/manga/namaikazikari.png'
import Naruto from '../assets/manga/naruto.png'
import OldMasterQ from '../assets/manga/oldmasterq.png'
import OnePiece from '../assets/manga/onepiece.png'
import Orange from '../assets/manga/orange.png'
import PerfectHalf from '../assets/manga/perfecthalf.png'
import PlatinaEnd from '../assets/manga/platinaend.png'
import PrinceOfTennis from '../assets/manga/princeoftennis.png'
import ReLife from '../assets/manga/relife.png'
import RurouniKenshin from '../assets/manga/rurounikenshin.png'
import Sankarea from '../assets/manga/sankarea.png'
import ShamanKing from '../assets/manga/shamanking.png'
import SlamDunk from '../assets/manga/slamdunk.png'
import SoloLeveling from '../assets/manga/sololeveling.png'
import Taiyounoie from '../assets/manga/taiyounoie.png'
import Tasogareotomexamnesia from '../assets/manga/tasogareotomexamnesia.png'
import TheGamer from '../assets/manga/thegamer.png'
import TheStrongestWizard from '../assets/manga/thestrongestwizard.png'
import Thewordsstrongestfighterwhotriedtoohard from '../assets/manga/thewordsstrongestfighterwhotriedtoohard.png'
import UQHolder from '../assets/manga/uqholder.png'
import WorldTrigger from '../assets/manga/worldtrigger.png'
import Yasashiisekainotsukurikata from '../assets/manga/yasashiisekainotsukurikata.png'
import Yuyuhakusho from '../assets/manga/yuyuhakusho.png'


export const MangaList = [
    {
        name: '',
        image: ,
        link: ''
    },
    {
        name: '',
        image: ,
        link: ''
    },

]